# Generated by Django 5.1.15 on 2026-07-23 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('CHAT', 'Chat'), ('ONSITE', 'On-site')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING_ESTIMATE', 'Pending estimate'), ('ESTIMATED', 'Estimate provided'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], max_length=20)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estimate_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='providers.serviceoffering')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='providers.serviceprovider')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'status', 'start_at'], name='booking_boo_provide_e2da5f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('start_at__isnull', True), ('end_at__gt', models.F('start_at')), _connector='OR'), name='booking_end_after_start')],
            },
        ),
    ]
