# Generated by Django 4.0.1 on 2023-10-07 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
        ('authentication', '0004_alter_userprofile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(upload_to='user/profile_photo'),
        ),
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(null=True)),
                ('address_lane_1', models.CharField(max_length=300)),
                ('address_lane_2', models.CharField(max_length=300)),
                ('pincode', models.CharField(max_length=50)),
                ('profile_photo', models.ImageField(upload_to='worker/profile_photo')),
                ('qualification_name', models.CharField(max_length=100)),
                ('qualification_doc', models.FileField(upload_to='worker/qualification_doc')),
                ('certification_name', models.CharField(max_length=100)),
                ('certification_doc', models.FileField(upload_to='worker/certification_doc')),
                ('license_name', models.CharField(max_length=100)),
                ('license_doc', models.FileField(upload_to='worker/license_doc')),
                ('experience', models.IntegerField()),
                ('health_insurance_name', models.CharField(max_length=100)),
                ('health_insurance_doc', models.FileField(upload_to='worker/health_insurance_doc')),
                ('emergency_service', models.BooleanField(default=False)),
                ('preferred_location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service.servicelocation')),
                ('service_time', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service.servicetime')),
                ('services_providing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.services')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
