# Generated by Django 4.0.1 on 2023-10-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_userprofile_profile_photo_workerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='experience',
            field=models.IntegerField(null=True),
        ),
    ]
