# Generated by Django 4.0.1 on 2023-10-07 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
        ('authentication', '0006_alter_workerprofile_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='certification_doc',
            field=models.FileField(null=True, upload_to='worker/certification_doc'),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='certification_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='health_insurance_doc',
            field=models.FileField(null=True, upload_to='worker/health_insurance_doc'),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='health_insurance_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='license_doc',
            field=models.FileField(null=True, upload_to='worker/license_doc'),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='license_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='preferred_location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.servicelocation'),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='qualification_doc',
            field=models.FileField(null=True, upload_to='worker/qualification_doc'),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='qualification_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='service_time',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.servicetime'),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='services_providing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.services'),
        ),
    ]
