# Generated by Django 4.0.1 on 2023-10-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
        ('authentication', '0007_alter_workerprofile_certification_doc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerprofile',
            name='services_providing',
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='services_providing',
            field=models.ManyToManyField(null=True, to='service.Services'),
        ),
    ]
